# Generated by Django 6.0.3 on 2026-03-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('contact_type', models.CharField(choices=[('client', 'Client'), ('prospect', 'Prospect')], db_index=True, max_length=10)),
                ('stage', models.CharField(blank=True, choices=[('lead', 'Lead'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('closing', 'Closing')], default='', max_length=10)),
                ('temperature', models.CharField(blank=True, choices=[('', 'None'), ('hot', 'Hot'), ('warm', 'Warm'), ('new', 'New')], default='', max_length=5)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('health', models.IntegerField(blank=True, help_text='0-100, only for clients', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('meeting_type', models.CharField(choices=[('group', 'Group'), ('one-on-one', 'One-on-one'), ('follow-up', 'Follow-up')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings', to='api.crmcontact')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
