# Generated by Django 5.1.15 on 2026-08-26 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_crmcontact_crmmeeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('attendees', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], db_index=True, default='draft', max_length=10)),
                ('stance', models.CharField(blank=True, choices=[('risk_on', 'Risk On'), ('neutral', 'Neutral'), ('risk_off', 'Risk Off')], default='', max_length=10)),
                ('macro_view', models.TextField(blank=True, default='')),
                ('portfolio_view', models.TextField(blank=True, default='')),
                ('risks', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('target_allocation', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=200)),
                ('asset_class', models.CharField(blank=True, default='', max_length=50)),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('add', 'Add'), ('trim', 'Trim'), ('sell', 'Sell'), ('hold', 'Hold'), ('hedge', 'Hedge'), ('watch', 'Watch'), ('research', 'Research')], default='watch', max_length=10)),
                ('target_weight_pct', models.FloatField(blank=True, null=True)),
                ('limit_price', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True, default='')),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially executed'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='api.committeemeeting')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=300)),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='api.committeemeeting')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
