# Generated by Django 4.2.16 on 2026-03-25 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0014_add_dashboard_url_to_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloombergApiQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('calls_ref', models.IntegerField(default=0)),
                ('calls_bdh', models.IntegerField(default=0)),
                ('calls_total', models.IntegerField(default=0)),
                ('limit_daily', models.IntegerField(default=50000, help_text='Max API calls per day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Quota',
                'verbose_name_plural': 'API Quotas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BloombergAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_bbg', models.CharField(db_index=True, help_text='Bloomberg ticker, e.g. "SPX Index", "/ISIN/US912810RA88"', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('asset_group', models.CharField(db_index=True, help_text='Grouping key, e.g. "Equity", "FixedIncome"', max_length=100)),
                ('is_vintage', models.BooleanField(default=False, help_text='Use vintage terminal (port 50001) instead of main (port 50000)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(blank=True, help_text='Optional link to existing Stock model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bbg_assets', to='finance.stock')),
            ],
            options={
                'verbose_name': 'Bloomberg Asset',
                'ordering': ['asset_group', 'code_bbg'],
            },
        ),
        migrations.CreateModel(
            name='BloombergField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name, e.g. "YieldToWorst"', max_length=100, unique=True)),
                ('bbg_fld', models.CharField(help_text='Bloomberg mnemonic, e.g. "INDEX_YIELD_TO_WORST"', max_length=100)),
                ('method', models.CharField(choices=[('ref', 'Reference (snapshot)'), ('bdh', 'Historical (time series)')], max_length=3)),
                ('sph', models.CharField(choices=[('Hist', 'Historical'), ('Set', 'Static/Setting')], help_text='Hist = time series rows, Set = single current value', max_length=4)),
                ('frequency', models.CharField(blank=True, default='1D', help_text='Update frequency: "1D", "1W", "1M", "1Q", "1S", "1Y"', max_length=5)),
                ('overrides', models.JSONField(blank=True, default=list, help_text='BBG overrides as list of [field, value] pairs')),
                ('elements', models.JSONField(blank=True, default=list, help_text='BBG elements as list of [key, value] pairs')),
                ('offset_date_ref', models.IntegerField(default=0, help_text='Business day offset for date reference')),
                ('ref_period', models.CharField(blank=True, default='', help_text='Period format: "W", "M", "Q", "S", "Y" or empty', max_length=5)),
                ('factor', models.FloatField(blank=True, help_text='Multiplication factor for values (e.g. 100 for pct conversion)', null=True)),
                ('is_critical', models.BooleanField(default=False, help_text='Critical fields (prices) are fetched even at high quota usage')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bloomberg Field',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.CharField(db_index=True, max_length=255)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('trade_date', models.DateField(db_index=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('broker', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='bloomberg.bloombergasset')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bbg_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade',
                'ordering': ['-trade_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('total_nav', models.FloatField()),
                ('total_shares', models.FloatField()),
                ('nav_per_share', models.FloatField()),
                ('is_official', models.BooleanField(default=False, help_text='True if this is the official/audited NAV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Internal NAV',
                'verbose_name_plural': 'Internal NAVs',
                'ordering': ['-date'],
                'unique_together': {('fund', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BloombergFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_group', models.CharField(db_index=True, max_length=100)),
                ('date_requested', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial (some assets failed)'), ('error', 'Error'), ('skipped', 'Skipped (not due yet)')], max_length=10)),
                ('assets_requested', models.IntegerField(default=0)),
                ('assets_succeeded', models.IntegerField(default=0)),
                ('assets_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('failed_assets', models.JSONField(blank=True, default=list, help_text='List of code_bbg tickers that failed')),
                ('api_calls_used', models.IntegerField(default=0)),
                ('terminal_used', models.CharField(default='main', help_text='"main" or "vintage"', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='bloomberg.bloombergfield')),
            ],
            options={
                'verbose_name': 'Fetch Log',
                'ordering': ['-date_requested', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BloombergFieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_group', models.CharField(db_index=True, max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='Start date for initial historical backfill (bdh)', null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_groups', to='bloomberg.bloombergfield')),
            ],
            options={
                'verbose_name': 'Field-Group Mapping',
                'ordering': ['asset_group', 'field__name'],
                'unique_together': {('asset_group', 'field')},
            },
        ),
        migrations.CreateModel(
            name='BloombergDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('date_ref', models.CharField(blank=True, default='', help_text='Period reference: "2026M03", "2026Q01", etc.', max_length=20)),
                ('value', models.FloatField(blank=True, null=True)),
                ('value_str', models.CharField(blank=True, default='', help_text='For non-numeric values like credit ratings', max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='bloomberg.bloombergasset')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='bloomberg.bloombergfield')),
            ],
            options={
                'verbose_name': 'Data Point',
                'indexes': [models.Index(fields=['asset', 'field', 'date'], name='bloomberg_b_asset_i_f2d1e9_idx'), models.Index(fields=['date', 'field'], name='bloomberg_b_date_fae614_idx')],
                'unique_together': {('asset', 'field', 'date', 'date_ref')},
            },
        ),
        migrations.CreateModel(
            name='BloombergAssetException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_value', models.FloatField(blank=True, help_text='Use this fixed value instead of fetching from BBG', null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='bloomberg.bloombergasset')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='bloomberg.bloombergfield')),
                ('proxy_asset', models.ForeignKey(blank=True, help_text='Fetch this field from a proxy asset instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_for', to='bloomberg.bloombergasset')),
                ('proxy_field', models.ForeignKey(blank=True, help_text='Use this BBG field on the proxy asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_for', to='bloomberg.bloombergfield')),
            ],
            options={
                'verbose_name': 'Asset Field Exception',
                'unique_together': {('asset', 'field')},
            },
        ),
    ]
