# Generated by Django 4.2.16 on 2026-03-25 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloomberg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloombergasset',
            name='asset_class',
            field=models.CharField(blank=True, default='', help_text='Equity, Fixed Income, Commodities, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='asset_market',
            field=models.CharField(blank=True, default='', help_text='STOCK, BOND, ETF, FUND, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='asset_origin',
            field=models.CharField(blank=True, default='', help_text='Short ticker without security type, e.g. "GLD US"', max_length=100),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='calendar',
            field=models.CharField(default='US', help_text='Trading calendar code', max_length=10),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='code_id',
            field=models.CharField(blank=True, default='', help_text='CNPJ, ISIN, or internal ID', max_length=100),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='contract_size',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='country',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='investment_strategy',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='is_discretionary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='liquidity',
            field=models.CharField(blank=True, default='', help_text='0-1 day, 1-7 days, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='obs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='option_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='option_strike',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='option_style',
            field=models.CharField(blank=True, choices=[('', 'None'), ('american', 'American'), ('european', 'European')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='option_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('call', 'Call'), ('put', 'Put')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='option_underlying',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='bloomberg.bloombergasset'),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='quote_bdays_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='quote_bdays_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='quote_cdays_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='quote_cdays_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='request_bbg_data',
            field=models.BooleanField(default=True, help_text='Whether to fetch data from Bloomberg'),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='risk_currency',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='risk_level',
            field=models.IntegerField(blank=True, help_text='1-5 scale', null=True),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='risk_weight',
            field=models.FloatField(default=100, help_text='Market exposure weight %'),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='security_type',
            field=models.CharField(blank=True, default='', help_text='Common Stock, Corp Bond, Govt Bond, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='settle_bdays_in',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='settle_bdays_out',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='settle_cdays_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloombergasset',
            name='settle_cdays_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='amount',
            field=models.FloatField(blank=True, help_text='Trade notional amount', null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='asset_ticker_raw',
            field=models.CharField(blank=True, default='', help_text='Ticker as typed by PM (used when asset not registered)', max_length=255),
        ),
        migrations.AddField(
            model_name='trade',
            name='cash_amount',
            field=models.FloatField(blank=True, help_text='Actual cash impact including fees (signed)', null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='clean_price',
            field=models.FloatField(blank=True, help_text='Clean price for bonds', null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='cmd',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='fee_per_unit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='fee_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='portfolio',
            field=models.CharField(blank=True, default='', help_text='Investment book: DISCRETIONARY, ETF FI Book, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='trade',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checked', 'Checked'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='trade',
            name='trader',
            field=models.CharField(blank=True, default='', help_text='Who placed the trade (distinct from entered_by)', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloombergasset',
            name='asset_group',
            field=models.CharField(db_index=True, help_text='Grouping key, e.g. "Stock", "Bond", "ETF"', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloombergasset',
            name='code_bbg',
            field=models.CharField(db_index=True, help_text='Bloomberg ticker, e.g. "GLD US EQUITY", "/ISIN/US912810RA88"', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='bloombergasset',
            name='is_vintage',
            field=models.BooleanField(default=False, help_text='Use vintage terminal (port 50001)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Null if asset not yet registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='bloomberg.bloombergasset'),
        ),
        migrations.CreateModel(
            name='AssetRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_raw', models.CharField(help_text='Ticker as entered by the PM', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Set once backoffice creates the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_requests', to='bloomberg.bloombergasset')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_completions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_from_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_requests', to='bloomberg.trade')),
            ],
            options={
                'verbose_name': 'Asset Registration Request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetRiskProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_type', models.CharField(choices=[('stress_911', 'Stress Test - 9/11'), ('stress_subprime', 'Stress Test - Subprime'), ('stress_covid', 'Stress Test - Covid'), ('correlation', 'Correlation Matrix'), ('var', 'VaR')], max_length=20)),
                ('ticker_proxy', models.CharField(max_length=100)),
                ('weight_or_beta', models.FloatField(default=1.0, help_text='Beta for stress tests, Weight for correlation/VaR')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_proxies', to='bloomberg.bloombergasset')),
            ],
            options={
                'verbose_name': 'Asset Risk Proxy',
                'verbose_name_plural': 'Asset Risk Proxies',
                'ordering': ['asset', 'proxy_type'],
                'unique_together': {('asset', 'proxy_type', 'ticker_proxy')},
            },
        ),
    ]
