# Generated by Django 4.2.16 on 2026-03-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomberg', '0002_bloombergasset_asset_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloombergasset',
            name='is_bbg_ticker',
            field=models.BooleanField(default=True, help_text='True if code_bbg is a valid Bloomberg ticker'),
        ),
    ]
