# Generated by Django 4.2.16 on 2026-03-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloomberg', '0003_add_is_bbg_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('fund', models.CharField(db_index=True, max_length=255)),
                ('portfolio', models.CharField(blank=True, default='', max_length=100)),
                ('asset_group', models.CharField(blank=True, default='', max_length=100)),
                ('broker', models.CharField(blank=True, default='', max_length=255)),
                ('asset_market', models.CharField(blank=True, default='', max_length=50)),
                ('asset_ticker', models.CharField(db_index=True, max_length=255)),
                ('is_leveraged', models.BooleanField(default=False)),
                ('units_open', models.FloatField(default=0)),
                ('units_close', models.FloatField(default=0)),
                ('units_transaction', models.FloatField(default=0)),
                ('units_lending', models.FloatField(default=0)),
                ('units_margin', models.FloatField(default=0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('avg_cost', models.FloatField(blank=True, null=True)),
                ('price_open', models.FloatField(blank=True, null=True)),
                ('price_close', models.FloatField(blank=True, null=True)),
                ('price_open_source', models.CharField(blank=True, default='', max_length=50)),
                ('price_close_source', models.CharField(blank=True, default='', max_length=50)),
                ('price_open_date', models.DateField(blank=True, null=True)),
                ('price_close_date', models.DateField(blank=True, null=True)),
                ('price_open_official', models.BooleanField(default=True)),
                ('price_close_official', models.BooleanField(default=True)),
                ('delta_open', models.FloatField(blank=True, null=True)),
                ('delta_close', models.FloatField(blank=True, null=True)),
                ('underlying_price_open', models.FloatField(blank=True, null=True)),
                ('underlying_price_close', models.FloatField(blank=True, null=True)),
                ('contract_size', models.FloatField(default=1)),
                ('avg_price_transaction', models.FloatField(blank=True, null=True)),
                ('amount_open', models.FloatField(blank=True, null=True)),
                ('amount_close', models.FloatField(blank=True, null=True)),
                ('amount_transaction', models.FloatField(blank=True, null=True)),
                ('pnl_open_position', models.FloatField(blank=True, null=True)),
                ('pnl_transaction', models.FloatField(blank=True, null=True)),
                ('pnl_transaction_fee', models.FloatField(blank=True, null=True)),
                ('pnl_dividend', models.FloatField(blank=True, null=True)),
                ('pnl_lending', models.FloatField(blank=True, null=True)),
                ('pnl_total', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_snapshots', to='bloomberg.bloombergasset')),
            ],
            options={
                'verbose_name': 'Position Snapshot',
                'ordering': ['-date', 'fund', 'asset_ticker'],
                'indexes': [models.Index(fields=['date', 'fund'], name='bloomberg_p_date_91d5cc_idx'), models.Index(fields=['asset_ticker'], name='bloomberg_p_asset_t_6b6dd3_idx')],
                'unique_together': {('date', 'fund', 'asset_ticker', 'portfolio')},
            },
        ),
    ]
