# Generated by Django 4.2.28 on 2026-03-02 17:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10, unique=True)),
                ("company_name", models.CharField(max_length=255)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("current_price", models.FloatField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvestmentThesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="A short abstract of the overall thesis."
                    ),
                ),
                (
                    "bull_case",
                    models.TextField(
                        help_text="Markdown supported detailed bull case."
                    ),
                ),
                (
                    "bear_case",
                    models.TextField(
                        help_text="Markdown supported detailed pre-mortem / bear case."
                    ),
                ),
                (
                    "conviction",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium-Low"),
                            (3, "Medium"),
                            (4, "Medium-High"),
                            (5, "High"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "analyst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theses",
                        to="finance.stock",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Investment Theses",
                "unique_together": {("stock", "analyst")},
            },
        ),
        migrations.CreateModel(
            name="Estimate5Y",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_pe_multiple",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                ("target_eps", models.FloatField()),
                (
                    "accumulated_dividends_5y",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "thesis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimates_5y",
                        to="finance.investmentthesis",
                    ),
                ),
            ],
        ),
    ]
