# Generated by Django 4.2.28 on 2026-03-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_stock_forward_pe_portfolioitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="financials",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
