# Generated by Django 4.2.28 on 2026-03-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_stock_financials"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="previous_close",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
