# Generated by Django 4.2.28 on 2026-03-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_stock_previous_close"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentthesis",
            name="valuation_json",
            field=models.JSONField(
                blank=True,
                help_text="Stores SOTP segments, DCF parameters, etc.",
                null=True,
            ),
        ),
    ]
