# Generated by Django 4.2.28 on 2026-03-02 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_investmentthesis_valuation_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investmentthesis",
            name="valuation_json",
        ),
        migrations.CreateModel(
            name="ValuationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_data", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuation_model",
                        to="finance.stock",
                    ),
                ),
            ],
        ),
    ]
