# Generated by Django 4.2.28 on 2026-03-04 20:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_remove_investmentthesis_valuation_json_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="asset_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="chg_pct_1d",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="cross_usd",
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="isin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="market_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="pnl_1d",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="specific_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="ticker",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="yield_to_worst",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="average_cost",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portfolio_entries",
                to="finance.stock",
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="finance.portfoliosnapshot",
            ),
        ),
    ]
