# Generated by Django 4.2.28 on 2026-03-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_portfoliosnapshot_portfolioitem_asset_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioitem",
            name="pe_next_12_months",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
