# Generated by Django 4.2.28 on 2026-03-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_portfolioitem_pe_next_12_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioitem",
            name="best_eps",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="eps_lt_growth",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="rating",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
