# Generated by Django 4.2.28 on 2026-03-05 18:53
import os
from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    username = os.environ.get('DJANGO_SUPERUSER_USERNAME', '')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD', '')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL', '')
    if not username or not password:
        return  # Skip if env vars not set
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username=username).exists():
        User.objects.create(
            username=username,
            email=email,
            password=make_password(password),
            is_superuser=True,
            is_staff=True
        )

def remove_superuser(apps, schema_editor):
    username = os.environ.get('DJANGO_SUPERUSER_USERNAME', '')
    if username:
        User = apps.get_model('auth', 'User')
        User.objects.filter(username=username).delete()

class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_moatscore_moatranking"),
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_code=remove_superuser),
    ]
