# Generated by Django 4.2.28 on 2026-03-05 18:53

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='gabriel').exists():
        User.objects.create(
            username='gabriel',
            email='***REDACTED_EMAIL***',
            password=make_password('***REDACTED***'),
            is_superuser=True,
            is_staff=True
        )

def remove_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='gabriel').delete()

class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_moatscore_moatranking"),
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_code=remove_superuser),
    ]
