from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_create_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistCashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('fund', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_account', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('counterparty_account', models.CharField(blank=True, max_length=255, null=True)),
                ('is_manual', models.BooleanField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('cmd', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistIndexPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_asset_info_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('fund', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
                ('st_value', models.CharField(blank=True, max_length=255, null=True)),
                ('flt_value', models.FloatField(blank=True, null=True)),
                ('bln_value', models.BooleanField(blank=True, null=True)),
                ('dte_value', models.DateField(blank=True, null=True)),
                ('column1', models.TextField(blank=True, null=True)),
                ('column2', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetPositionHistOfficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('fund', models.CharField(blank=True, max_length=255, null=True)),
                ('portfolio', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_group', models.CharField(blank=True, max_length=255, null=True)),
                ('broker', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_market', models.CharField(blank=True, max_length=255, null=True)),
                ('asset', models.CharField(blank=True, max_length=255, null=True)),
                ('is_leveraged_product', models.BooleanField(blank=True, null=True)),
                ('units_open', models.FloatField(blank=True, null=True)),
                ('units_close', models.FloatField(blank=True, null=True)),
                ('units_transaction', models.FloatField(blank=True, null=True)),
                ('units_lending', models.FloatField(blank=True, null=True)),
                ('units_margin', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('avg_cost', models.FloatField(blank=True, null=True)),
                ('price_open', models.FloatField(blank=True, null=True)),
                ('price_close', models.FloatField(blank=True, null=True)),
                ('price_open_source', models.CharField(blank=True, max_length=100, null=True)),
                ('price_close_source', models.CharField(blank=True, max_length=100, null=True)),
                ('price_open_date', models.DateField(blank=True, null=True)),
                ('price_close_date', models.DateField(blank=True, null=True)),
                ('price_opens_official', models.FloatField(blank=True, null=True)),
                ('price_closes_official', models.FloatField(blank=True, null=True)),
                ('delta_open', models.FloatField(blank=True, null=True)),
                ('delta_close', models.FloatField(blank=True, null=True)),
                ('underlying_price_open', models.FloatField(blank=True, null=True)),
                ('underlying_price_close', models.FloatField(blank=True, null=True)),
                ('contract_size', models.FloatField(blank=True, null=True)),
                ('avg_price_transaction', models.FloatField(blank=True, null=True)),
                ('amount_open', models.FloatField(blank=True, null=True)),
                ('amount_close', models.FloatField(blank=True, null=True)),
                ('amount_transaction', models.FloatField(blank=True, null=True)),
                ('pnl_open_position', models.FloatField(blank=True, null=True)),
                ('pnl_transaction', models.FloatField(blank=True, null=True)),
                ('pnl_transaction_fee', models.FloatField(blank=True, null=True)),
                ('pnl_dividend', models.FloatField(blank=True, null=True)),
                ('pnl_lending', models.FloatField(blank=True, null=True)),
                ('pnl_total', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
