# Generated by Django 4.2.28 on 2026-03-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_add_hist_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="NAVPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("nav", models.FloatField(blank=True, null=True)),
                ("shares", models.FloatField(blank=True, null=True)),
                ("nav_per_share", models.FloatField(blank=True, null=True)),
                ("subscription_d0", models.FloatField(blank=True, null=True)),
                ("redemption_d0", models.FloatField(blank=True, null=True)),
                ("redemption_d1", models.FloatField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
