# Generated by Django 4.2.28 on 2026-03-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_add_nav_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="dashboard_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="assetpositionhistofficial",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="histcashtransaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="histindexprice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
