# Generated by Django 5.1.15 on 2026-06-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alpha_data_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('cash', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily cash balances',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FundConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.CharField(default='IGF TR', max_length=255)),
                ('shares', models.FloatField(default=32435667)),
                ('mgmt_fee_rate', models.FloatField(default=0.01)),
                ('trading_days', models.IntegerField(default=255)),
                ('perf_fee_rate', models.FloatField(default=0.1)),
                ('high_water_mark', models.FloatField(default=1.1364)),
                ('mgmt_fee_paid_through', models.DateField(blank=True, null=True)),
                ('perf_fee_paid_through', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fund configuration',
                'verbose_name_plural': 'Fund configuration',
            },
        ),
    ]
