# Generated by Django 5.1.15 on 2026-08-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_fundconfig_base_cotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualFundFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('subscription', models.FloatField(default=0.0)),
                ('redemption', models.FloatField(default=0.0)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Manual fund flows',
                'ordering': ['date'],
            },
        ),
        migrations.RenameIndex(
            model_name='alphadatapoint',
            new_name='finance_alp_stock_233d1a_idx',
            old_name='finance_alp_stock_d57a36_idx',
        ),
    ]
