# Generated by Django 5.1.15 on 2026-08-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_manual_fund_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundconfig',
            name='flow_share_convention',
            field=models.CharField(choices=[('prev_cota', 'Cota do dia anterior (D0 pela cota de D-1)'), ('same_cota', 'Cota do próprio dia (ex-fluxo)')], default='prev_cota', max_length=20),
        ),
    ]
