# Generated by Django 5.1.15 on 2026-08-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_flow_share_convention'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='chg_pct_ytd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
