# Generated by Django 4.2.28 on 2026-10-08 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0022_portfolioitem_chg_pct_ytd"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNAVReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("base_nav", models.FloatField(blank=True, null=True)),
                ("mgmt_fee", models.FloatField(blank=True, null=True)),
                ("perf_fee", models.FloatField(blank=True, null=True)),
                ("nav", models.FloatField(blank=True, null=True)),
                ("subscriptions", models.FloatField(blank=True, null=True)),
                ("redemptions", models.FloatField(blank=True, null=True)),
                ("nav_closing", models.FloatField(blank=True, null=True)),
                ("prev_nav_closing", models.FloatField(blank=True, null=True)),
                ("prev_subscriptions", models.FloatField(blank=True, null=True)),
                ("total_assets", models.FloatField(blank=True, null=True)),
                ("total_shares", models.FloatField(blank=True, null=True)),
                ("lead_cota", models.FloatField(blank=True, null=True)),
                ("lead_table", models.JSONField(blank=True, default=dict)),
                ("series", models.JSONField(blank=True, default=list)),
                ("holdings", models.JSONField(blank=True, default=list)),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="AssetAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_id",
                    models.CharField(
                        help_text='Internal id, e.g. "QQQ" or "PEMEX 5.95 01/28/31"',
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("Equity", "Equity"),
                            ("Fixed Income", "Fixed Income"),
                            ("Other", "Other"),
                        ],
                        default="Equity",
                        max_length=20,
                    ),
                ),
                (
                    "sub_class",
                    models.CharField(
                        blank=True,
                        default="Stock",
                        help_text="Stock, Index ETF, Thematic ETF, HY ETF, Corporate Bond, Sovereign Bond, US Treasury",
                        max_length=40,
                    ),
                ),
                ("sector", models.CharField(blank=True, default="", max_length=60)),
                (
                    "isin",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "statement_pattern",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Regex matched against the bank statement description (used when the ISIN is absent)",
                        max_length=255,
                    ),
                ),
                (
                    "tickers",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Comma-separated aliases used by Bloomberg snapshots / position history, e.g. "SDHA LN EQUITY,SDHA LN"',
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["asset_class", "asset_id"],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(db_index=True, default="", max_length=64)),
                ("trade_date", models.DateField(db_index=True)),
                ("trade_time", models.CharField(blank=True, default="", max_length=16)),
                ("booking_date", models.DateField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("amount", models.FloatField()),
                ("balance", models.FloatField(blank=True, null=True)),
                ("txn_no", models.CharField(blank=True, default="", max_length=64)),
                ("desc1", models.TextField(blank=True, default="")),
                ("desc2", models.TextField(blank=True, default="")),
                ("desc3", models.TextField(blank=True, default="")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BUY", "BUY"),
                            ("SELL", "SELL"),
                            ("REDEMPTION", "REDEMPTION"),
                            ("AMORTIZATION", "AMORTIZATION"),
                            ("DIVIDEND", "DIVIDEND"),
                            ("COUPON", "COUPON"),
                            ("SUBSCRIPTION", "SUBSCRIPTION"),
                            ("REDEMPTION_PAID", "REDEMPTION_PAID"),
                            ("MGMT_FEE", "MGMT_FEE"),
                            ("MGMT_PERF_FEE", "MGMT_PERF_FEE"),
                            ("EXPENSE", "EXPENSE"),
                            ("BANK_FEE", "BANK_FEE"),
                            ("BANK_INTEREST", "BANK_INTEREST"),
                            ("TRANSFER", "TRANSFER"),
                            ("OTHER_INCOME", "OTHER_INCOME"),
                            ("OTHER", "OTHER"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "type_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BUY", "BUY"),
                            ("SELL", "SELL"),
                            ("REDEMPTION", "REDEMPTION"),
                            ("AMORTIZATION", "AMORTIZATION"),
                            ("DIVIDEND", "DIVIDEND"),
                            ("COUPON", "COUPON"),
                            ("SUBSCRIPTION", "SUBSCRIPTION"),
                            ("REDEMPTION_PAID", "REDEMPTION_PAID"),
                            ("MGMT_FEE", "MGMT_FEE"),
                            ("MGMT_PERF_FEE", "MGMT_PERF_FEE"),
                            ("EXPENSE", "EXPENSE"),
                            ("BANK_FEE", "BANK_FEE"),
                            ("BANK_INTEREST", "BANK_INTEREST"),
                            ("TRANSFER", "TRANSFER"),
                            ("OTHER_INCOME", "OTHER_INCOME"),
                            ("OTHER", "OTHER"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("asset_id", models.CharField(blank=True, default="", max_length=64)),
                ("units", models.FloatField(default=0.0)),
                ("price", models.FloatField(blank=True, null=True)),
                ("accrued", models.FloatField(blank=True, null=True)),
                ("is_reversal", models.BooleanField(default=False)),
                (
                    "counterparty",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["trade_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="ManualLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BUY", "BUY"),
                            ("SELL", "SELL"),
                            ("DIVIDEND", "DIVIDEND"),
                            ("COUPON", "COUPON"),
                            ("REDEMPTION", "REDEMPTION"),
                            ("EXPENSE", "EXPENSE"),
                            ("OTHER_INCOME", "OTHER_INCOME"),
                        ],
                        max_length=20,
                    ),
                ),
                ("asset_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "units",
                    models.FloatField(default=0.0, help_text="+ bought / - sold"),
                ),
                (
                    "amount",
                    models.FloatField(
                        help_text="Cash in USD, signed: + received, - paid"
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["trade_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("duration_s", models.FloatField(default=0.0)),
                ("ok", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="fundconfig",
            name="perf_cutover_date",
            field=models.DateField(
                blank=True, default=datetime.date(2026, 3, 24), null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.UniqueConstraint(
                fields=("account", "txn_no", "amount", "trade_date"),
                name="uniq_bank_txn",
            ),
        ),
    ]
